import { APIGatewayAuthorizerEvent } from "aws-lambda";
export default function createApiEvent(): APIGatewayAuthorizerEvent {
  let apiEvent: any = {
    type: "REQUEST",
    methodArn:
      "arn:aws:execute-api:eu-west-1:022113623934:lwannaj5z9/qa/GET/users/hellojwtlambda",
    resource: "/users/hellojwtlambda",
    path: "/users/hellojwtlambda",
    httpMethod: "GET",
    headers: {
      Authorization:
        "Bearer eyJraWQiOiIyQTV6U1VCMDQ1OHRzYzluMjZWOUk5WGlSNU5pbllNVVdHUG9YZVBhQTVJPSIsImFsZyI6IlJTMjU2In0.eyJzdWIiOiI5MjU0NjU5Ni1kMjc0LTQ5YTctYjJiNS1kYWVlZTBiMWVlZGMiLCJpc3MiOiJodHRwczpcL1wvY29nbml0by1pZHAuZXUtd2VzdC0xLmFtYXpvbmF3cy5jb21cL2V1LXdlc3QtMV9tR3YyOVoyZnkiLCJjbGllbnRfaWQiOiI0ZTM5ZnFlaHZsazFuNG1pMjRndHBhMHRsOCIsIm9yaWdpbl9qdGkiOiI4MDE3YTc5MC02MTE1LTRjN2YtOGQyYy1kZWVhNDE1MDE5NGYiLCJldmVudF9pZCI6ImY1ZTU1NDExLTBjNDYtNGU4OC1iYzBmLTkwMzNlYzg0NjkzYiIsInRva2VuX3VzZSI6ImFjY2VzcyIsInNjb3BlIjoiYXdzLmNvZ25pdG8uc2lnbmluLnVzZXIuYWRtaW4iLCJhdXRoX3RpbWUiOjE2NTYyNDk3NDEsImV4cCI6MTY1NjI1MzM0MSwiaWF0IjoxNjU2MjQ5NzQxLCJqdGkiOiJiOTRjOGY5OS0yOTBkLTRkOGMtOTgyYy1lZTJjNmVjODdjNjQiLCJ1c2VybmFtZSI6Im11aGFtZWQuc3VsZW1hbiJ9.t0HjQPQjDQayrRfrKKLBdG7_DWlg5jMlcLb47NihXwP3844P5gaXZERDTrY9QJvTA21gewajfyAn8jUK6m6VuFhEmz4gdP-NWzKkLYjKP2qznVjM7yiojFRbI6H_qHlyUT_mr_Tx2NsOvDw7Z02yXMCmEi2Xj9I4kWpg_IymvpsVOJHJSSoHHqvvOAumF4-siOfw-pVJm9Og98Lhd6fVDyi7bFZEDwOyaOyC_6jAUaJs4vjdjGxjvrA8xKDy2AMwqrel4Sm51uyxSOncwLyh1h3rgsV9ZrHkSX60lyDDwlJi5dKsB_qeB2Ylb3AVC6Sq-3sDZl4FY6TPNRE-q6ZW7A",
      "CloudFront-Forwarded-Proto": "https",
      "CloudFront-Is-Desktop-Viewer": "true",
      "CloudFront-Is-Mobile-Viewer": "false",
      "CloudFront-Is-SmartTV-Viewer": "false",
      "CloudFront-Is-Tablet-Viewer": "false",
      "CloudFront-Viewer-Country": "IE",
      Host: "lwannaj5z9.execute-api.eu-west-1.amazonaws.com",
      "User-Agent": "Amazon CloudFront",
      Via: "1.1 b3f1989dace51bd45b636bc99a604b20.cloudfront.net (CloudFront)",
      "X-Amz-Cf-Id": "z8JhVgrHzEyUsMcwunFG7Or3mLM_zMgmJ_XSqbAydwQsH8ei3Id-ow==",
      "X-Amzn-Trace-Id": "Root=1-62b85d8d-0c057c550963bc7c749f4aef",
      "X-Forwarded-For": "34.253.97.102, 64.252.133.35",
      "X-Forwarded-Port": "443",
      "X-Forwarded-Proto": "https",
    },
    multiValueHeaders: {
      Authorization: [
        "Bearer eyJraWQiOiIyQTV6U1VCMDQ1OHRzYzluMjZWOUk5WGlSNU5pbllNVVdHUG9YZVBhQTVJPSIsImFsZyI6IlJTMjU2In0.eyJzdWIiOiI5MjU0NjU5Ni1kMjc0LTQ5YTctYjJiNS1kYWVlZTBiMWVlZGMiLCJpc3MiOiJodHRwczpcL1wvY29nbml0by1pZHAuZXUtd2VzdC0xLmFtYXpvbmF3cy5jb21cL2V1LXdlc3QtMV9tR3YyOVoyZnkiLCJjbGllbnRfaWQiOiI0ZTM5ZnFlaHZsazFuNG1pMjRndHBhMHRsOCIsIm9yaWdpbl9qdGkiOiI4MDE3YTc5MC02MTE1LTRjN2YtOGQyYy1kZWVhNDE1MDE5NGYiLCJldmVudF9pZCI6ImY1ZTU1NDExLTBjNDYtNGU4OC1iYzBmLTkwMzNlYzg0NjkzYiIsInRva2VuX3VzZSI6ImFjY2VzcyIsInNjb3BlIjoiYXdzLmNvZ25pdG8uc2lnbmluLnVzZXIuYWRtaW4iLCJhdXRoX3RpbWUiOjE2NTYyNDk3NDEsImV4cCI6MTY1NjI1MzM0MSwiaWF0IjoxNjU2MjQ5NzQxLCJqdGkiOiJiOTRjOGY5OS0yOTBkLTRkOGMtOTgyYy1lZTJjNmVjODdjNjQiLCJ1c2VybmFtZSI6Im11aGFtZWQuc3VsZW1hbiJ9.t0HjQPQjDQayrRfrKKLBdG7_DWlg5jMlcLb47NihXwP3844P5gaXZERDTrY9QJvTA21gewajfyAn8jUK6m6VuFhEmz4gdP-NWzKkLYjKP2qznVjM7yiojFRbI6H_qHlyUT_mr_Tx2NsOvDw7Z02yXMCmEi2Xj9I4kWpg_IymvpsVOJHJSSoHHqvvOAumF4-siOfw-pVJm9Og98Lhd6fVDyi7bFZEDwOyaOyC_6jAUaJs4vjdjGxjvrA8xKDy2AMwqrel4Sm51uyxSOncwLyh1h3rgsV9ZrHkSX60lyDDwlJi5dKsB_qeB2Ylb3AVC6Sq-3sDZl4FY6TPNRE-q6ZW7A",
      ],
      "CloudFront-Forwarded-Proto": ["https"],
      "CloudFront-Is-Desktop-Viewer": ["true"],
      "CloudFront-Is-Mobile-Viewer": ["false"],
      "CloudFront-Is-SmartTV-Viewer": ["false"],
      "CloudFront-Is-Tablet-Viewer": ["false"],
      "CloudFront-Viewer-Country": ["IE"],
      Host: ["lwannaj5z9.execute-api.eu-west-1.amazonaws.com"],
      "User-Agent": ["Amazon CloudFront"],
      Via: ["1.1 b3f1989dace51bd45b636bc99a604b20.cloudfront.net (CloudFront)"],
      "X-Amz-Cf-Id": [
        "z8JhVgrHzEyUsMcwunFG7Or3mLM_zMgmJ_XSqbAydwQsH8ei3Id-ow==",
      ],
      "X-Amzn-Trace-Id": ["Root=1-62b85d8d-0c057c550963bc7c749f4aef"],
      "X-Forwarded-For": ["34.253.97.102, 64.252.133.35"],
      "X-Forwarded-Port": ["443"],
      "X-Forwarded-Proto": ["https"],
    },
    queryStringParameters: {},
    multiValueQueryStringParameters: {},
    pathParameters: {},
    stageVariables: {},
    requestContext: {
      resourceId: "v35snd",
      resourcePath: "/users/hellojwtlambda",
      httpMethod: "GET",
      extendedRequestId: "UVOOJGDgDoEFk-A=",
      requestTime: "26/Jun/2022:13:22:21 +0000",
      path: "/qa/users/hellojwtlambda",
      accountId: "022113623934",
      protocol: "HTTP/1.1",
      stage: "qa",
      domainPrefix: "lwannaj5z9",
      requestTimeEpoch: 1656249741576,
      requestId: "fa0f32fa-d24b-4aa3-bfbb-67bd62ad5b81",
      identity: {
        cognitoIdentityPoolId: null,
        accountId: null,
        cognitoIdentityId: null,
        caller: null,
        sourceIp: "34.253.97.102",
        principalOrgId: null,
        accessKey: null,
        cognitoAuthenticationType: null,
        cognitoAuthenticationProvider: null,
        userArn: null,
        userAgent: "Amazon CloudFront",
        user: null,
      },
      domainName: "lwannaj5z9.execute-api.eu-west-1.amazonaws.com",
      apiId: "lwannaj5z9",
    },
  };
  return apiEvent;
}
