version: 0.2

#env:
  #variables:
     # key: "value"
     # key: "value"
  #parameter-store:
     # key: "value"
     # key: "value"
  #secrets-manager:
     # key: secret-id:json-key:version-stage:version-id
     # key: secret-id:json-key:version-stage:version-id
  #exported-variables:
     # - variable
     # - variable
  #git-credential-helper: yes
#batch:
  #fast-fail: true
  #build-list:
  #build-matrix:
  #build-graph:
phases:
  install:
    #If you use the Ubuntu standard image 2.0 or later, you must specify runtime-versions.
    #If you specify runtime-versions and use an image other than Ubuntu standard image 2.0, the build fails.
    runtime-versions:
      nodejs: 12
      # name: version
      # name: version
    commands:
      - npm install -g serverless
      - npm install
      #- cd ${SERVICE_PATH} && npm install && cd -
      # - command
      # - command
  pre_build:
    commands:
      #- aws s3 cp s3://apigateway-debug-deployments/serverless_nodejs/office.zip --recursive | sort | tail -n 1 | awk '{print $4}' .
      - mkdir artifacts
      - aws s3 cp s3://apigateway-debug-deployments/serverless_nodejs/office.zip ./artifacts/
      - aws s3 cp s3://apigateway-debug-deployments/serverless_nodejs/serverless-state.json ./artifacts/
      - aws s3 cp s3://apigateway-debug-deployments/serverless_nodejs/serverless.yml ./artifacts/
      - aws s3 cp s3://apigateway-debug-deployments/serverless_nodejs/cloudformation-template-update-stack.json ./artifacts/
      - echo 'downladed completed'
      # - command
      # - command
  build:
    commands:
      - STAGE_NAME=${CODEBUILD_INITIATOR##*/}
      - serverless deploy --artifact ./artifacts/office.zip --force
      - echo 'serverless deployed'
  post_build:
    commands:
      - echo "bulid completed!"
      # - command
      # - command
#reports:
  #report-name-or-arn:
    #files:
      # - location
      # - location
    #base-directory: location
    #discard-paths: yes
    #file-format: JunitXml | CucumberJson
# artifacts:
#   files:
#     - artifacts/**/*
#     - serverless.yml
    # - serverless.yml
    # - package.json
    # - package-lock.json
    # - deploy.sh    
    # - location
    # - location
  # discard-paths: yes
  #name: $(date +%Y-%m-%d)
  #discard-paths: yes
  #base-directory: location
# cache:
#   paths:
#     - node_modules
#     #- ${SERVICE_PATH}/node_modules
#     #- paths